grpc_port: 9191
state_file: "cache.json"
operator_config: "eigen_operator_config.yaml"
network: "testnet"
eth_oracle:
  rpc:
    local: "http://127.0.0.1:8545"
    testnet: "https://rpc.ankr.com/eth_holesky"
    mainnet: "https://rpc.ankr.com/eth"
  contract_addrs:
    service_manager: "0xe2Aaf5A9a04cac7f3D43b4Afb7463850E1caEfB3"
    price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    redemption_trackers:
      ethereum: "0x0000000000000000000000000000000000000000"
  network_name: "Holešky Ethereum Testnet"
solana_rpc:
  testnet: "https://api.testnet.solana.com"
  mainnet: "https://api.mainnet-beta.solana.com/"
proxy_rpc:
  url: "http://127.0.0.1:1234"
  user: "user"
  password: "secret"
neutrino:
  path: "./neutrino"
