# this sets the logger level (true = info, false = debug)
production: true

operator_address: 0x86A69131998398874e528A9D4386C1145F83c8d3
operator_validator_address: zenvaloper16uhx7qes24xz8qzgpz6yhzvsj3zsevfaw7pj9r

# EigenLayer Slasher contract address

# This is the address of the contracts which are deployed in the anvil saved state
# The saved eigenlayer state is located in tests/anvil/credible_squaring_avs_deployment_output.json
# TODO(samlaf): automate updating these addresses when we deploy new contracts
avs_registry_coordinator_address: 0xD4BdE8DD7B82C04E4c1617B0F477f4F8B2CcdE2F
operator_state_retriever_address: 0x148e80620b9464Fa0731467d504A2F760E7242C8

# ETH RPC URL
eth_rpc_url: https://alien-fittest-dew.ethereum-holesky.quiknode.pro/83464d9ac98adf68666cc53b8f8743ad7309335e/
eth_ws_url: wss://alien-fittest-dew.ethereum-holesky.quiknode.pro/83464d9ac98adf68666cc53b8f8743ad7309335e/

# If you running this using eigenlayer CLI and the provided AVS packaging structure,
# this should be /operator_keys/ecdsa_key.json as the host path will be asked while running
#
# If you are running locally using go run main.go, this should be full path to your local ecdsa key file
ecdsa_private_key_store_path: keys/test.ecdsa.key.json

# If you running this using eigenlayer CLI and the provided AVS packaging structure,
# this should be /operator_keys/bls_key.json as the host path will be asked while running
#
# We are using bn254 curve for bls keys
#
# If you are running locally using go run main.go, this should be full path to your local bls key file
bls_private_key_store_path: keys/test.bls.key.json

# address which the aggregator listens on for operator signed messages
aggregator_server_ip_port_address: localhost:8090

eigen_metrics_ip_port_address: localhost:9292
enable_metrics: true
node_api_ip_port_address: localhost:9010
enable_node_api: true

# address of token to deposit tokens into when registering on startup
# addresses.erc20MockStrategy in tests/anvil/credible_squaring_avs_deployment_output.json
token_strategy_addr: 0x80528D6e9A2BAbFc766965E0E26d5aB08D9CFaF9

service_manager_address: 0xb48F00b89A4017f78794F35cb1ef540EDA5d201B