// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/sidecar_service.proto

package api

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LatestBitcoinBlockHeaderRequest struct {
	ChainName string `protobuf:"bytes,1,opt,name=ChainName,proto3" json:"ChainName,omitempty"`
}

func (m *LatestBitcoinBlockHeaderRequest) Reset()         { *m = LatestBitcoinBlockHeaderRequest{} }
func (m *LatestBitcoinBlockHeaderRequest) String() string { return proto.CompactTextString(m) }
func (*LatestBitcoinBlockHeaderRequest) ProtoMessage()    {}
func (*LatestBitcoinBlockHeaderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f890d7da2148de8, []int{0}
}
func (m *LatestBitcoinBlockHeaderRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LatestBitcoinBlockHeaderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LatestBitcoinBlockHeaderRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LatestBitcoinBlockHeaderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatestBitcoinBlockHeaderRequest.Merge(m, src)
}
func (m *LatestBitcoinBlockHeaderRequest) XXX_Size() int {
	return m.Size()
}
func (m *LatestBitcoinBlockHeaderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LatestBitcoinBlockHeaderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LatestBitcoinBlockHeaderRequest proto.InternalMessageInfo

func (m *LatestBitcoinBlockHeaderRequest) GetChainName() string {
	if m != nil {
		return m.ChainName
	}
	return ""
}

type BitcoinBlockHeaderByHeightRequest struct {
	BlockHeight int64  `protobuf:"varint,1,opt,name=BlockHeight,proto3" json:"BlockHeight,omitempty"`
	ChainName   string `protobuf:"bytes,2,opt,name=ChainName,proto3" json:"ChainName,omitempty"`
}

func (m *BitcoinBlockHeaderByHeightRequest) Reset()         { *m = BitcoinBlockHeaderByHeightRequest{} }
func (m *BitcoinBlockHeaderByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*BitcoinBlockHeaderByHeightRequest) ProtoMessage()    {}
func (*BitcoinBlockHeaderByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f890d7da2148de8, []int{1}
}
func (m *BitcoinBlockHeaderByHeightRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BitcoinBlockHeaderByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BitcoinBlockHeaderByHeightRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BitcoinBlockHeaderByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BitcoinBlockHeaderByHeightRequest.Merge(m, src)
}
func (m *BitcoinBlockHeaderByHeightRequest) XXX_Size() int {
	return m.Size()
}
func (m *BitcoinBlockHeaderByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BitcoinBlockHeaderByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BitcoinBlockHeaderByHeightRequest proto.InternalMessageInfo

func (m *BitcoinBlockHeaderByHeightRequest) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *BitcoinBlockHeaderByHeightRequest) GetChainName() string {
	if m != nil {
		return m.ChainName
	}
	return ""
}

type BitcoinBlockHeaderResponse struct {
	BlockHeader *BTCBlockHeader `protobuf:"bytes,1,opt,name=blockHeader,proto3" json:"blockHeader,omitempty"`
	BlockHeight int64           `protobuf:"varint,2,opt,name=BlockHeight,proto3" json:"BlockHeight,omitempty"`
	TipHeight   int64           `protobuf:"varint,3,opt,name=TipHeight,proto3" json:"TipHeight,omitempty"`
}

func (m *BitcoinBlockHeaderResponse) Reset()         { *m = BitcoinBlockHeaderResponse{} }
func (m *BitcoinBlockHeaderResponse) String() string { return proto.CompactTextString(m) }
func (*BitcoinBlockHeaderResponse) ProtoMessage()    {}
func (*BitcoinBlockHeaderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f890d7da2148de8, []int{2}
}
func (m *BitcoinBlockHeaderResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BitcoinBlockHeaderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BitcoinBlockHeaderResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BitcoinBlockHeaderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BitcoinBlockHeaderResponse.Merge(m, src)
}
func (m *BitcoinBlockHeaderResponse) XXX_Size() int {
	return m.Size()
}
func (m *BitcoinBlockHeaderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BitcoinBlockHeaderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BitcoinBlockHeaderResponse proto.InternalMessageInfo

func (m *BitcoinBlockHeaderResponse) GetBlockHeader() *BTCBlockHeader {
	if m != nil {
		return m.BlockHeader
	}
	return nil
}

func (m *BitcoinBlockHeaderResponse) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *BitcoinBlockHeaderResponse) GetTipHeight() int64 {
	if m != nil {
		return m.TipHeight
	}
	return 0
}

type BTCBlockHeader struct {
	Version    int64  `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	PrevBlock  string `protobuf:"bytes,2,opt,name=PrevBlock,proto3" json:"PrevBlock,omitempty"`
	MerkleRoot string `protobuf:"bytes,3,opt,name=MerkleRoot,proto3" json:"MerkleRoot,omitempty"`
	TimeStamp  int64  `protobuf:"varint,4,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	Bits       int64  `protobuf:"varint,5,opt,name=Bits,proto3" json:"Bits,omitempty"`
	Nonce      int64  `protobuf:"varint,6,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	BlockHash  string `protobuf:"bytes,7,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
}

func (m *BTCBlockHeader) Reset()         { *m = BTCBlockHeader{} }
func (m *BTCBlockHeader) String() string { return proto.CompactTextString(m) }
func (*BTCBlockHeader) ProtoMessage()    {}
func (*BTCBlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f890d7da2148de8, []int{3}
}
func (m *BTCBlockHeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BTCBlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BTCBlockHeader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BTCBlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BTCBlockHeader.Merge(m, src)
}
func (m *BTCBlockHeader) XXX_Size() int {
	return m.Size()
}
func (m *BTCBlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BTCBlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BTCBlockHeader proto.InternalMessageInfo

func (m *BTCBlockHeader) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BTCBlockHeader) GetPrevBlock() string {
	if m != nil {
		return m.PrevBlock
	}
	return ""
}

func (m *BTCBlockHeader) GetMerkleRoot() string {
	if m != nil {
		return m.MerkleRoot
	}
	return ""
}

func (m *BTCBlockHeader) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *BTCBlockHeader) GetBits() int64 {
	if m != nil {
		return m.Bits
	}
	return 0
}

func (m *BTCBlockHeader) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *BTCBlockHeader) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

type SidecarStateRequest struct {
}

func (m *SidecarStateRequest) Reset()         { *m = SidecarStateRequest{} }
func (m *SidecarStateRequest) String() string { return proto.CompactTextString(m) }
func (*SidecarStateRequest) ProtoMessage()    {}
func (*SidecarStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f890d7da2148de8, []int{4}
}
func (m *SidecarStateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SidecarStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SidecarStateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SidecarStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SidecarStateRequest.Merge(m, src)
}
func (m *SidecarStateRequest) XXX_Size() int {
	return m.Size()
}
func (m *SidecarStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SidecarStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SidecarStateRequest proto.InternalMessageInfo

type SidecarStateResponse struct {
	Delegations    []byte `protobuf:"bytes,1,opt,name=Delegations,proto3" json:"Delegations,omitempty"`
	ROCKUSDPrice   string `protobuf:"bytes,2,opt,name=ROCKUSDPrice,proto3" json:"ROCKUSDPrice,omitempty"`
	ETHUSDPrice    string `protobuf:"bytes,3,opt,name=ETHUSDPrice,proto3" json:"ETHUSDPrice,omitempty"`
	EthBlockHeight uint64 `protobuf:"varint,4,opt,name=EthBlockHeight,proto3" json:"EthBlockHeight,omitempty"`
	EthBlockHash   string `protobuf:"bytes,5,opt,name=EthBlockHash,proto3" json:"EthBlockHash,omitempty"`
	EthGasPrice    uint64 `protobuf:"varint,6,opt,name=EthGasPrice,proto3" json:"EthGasPrice,omitempty"`
	EthGasLimit    uint64 `protobuf:"varint,7,opt,name=EthGasLimit,proto3" json:"EthGasLimit,omitempty"`
}

func (m *SidecarStateResponse) Reset()         { *m = SidecarStateResponse{} }
func (m *SidecarStateResponse) String() string { return proto.CompactTextString(m) }
func (*SidecarStateResponse) ProtoMessage()    {}
func (*SidecarStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f890d7da2148de8, []int{5}
}
func (m *SidecarStateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SidecarStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SidecarStateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SidecarStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SidecarStateResponse.Merge(m, src)
}
func (m *SidecarStateResponse) XXX_Size() int {
	return m.Size()
}
func (m *SidecarStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SidecarStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SidecarStateResponse proto.InternalMessageInfo

func (m *SidecarStateResponse) GetDelegations() []byte {
	if m != nil {
		return m.Delegations
	}
	return nil
}

func (m *SidecarStateResponse) GetROCKUSDPrice() string {
	if m != nil {
		return m.ROCKUSDPrice
	}
	return ""
}

func (m *SidecarStateResponse) GetETHUSDPrice() string {
	if m != nil {
		return m.ETHUSDPrice
	}
	return ""
}

func (m *SidecarStateResponse) GetEthBlockHeight() uint64 {
	if m != nil {
		return m.EthBlockHeight
	}
	return 0
}

func (m *SidecarStateResponse) GetEthBlockHash() string {
	if m != nil {
		return m.EthBlockHash
	}
	return ""
}

func (m *SidecarStateResponse) GetEthGasPrice() uint64 {
	if m != nil {
		return m.EthGasPrice
	}
	return 0
}

func (m *SidecarStateResponse) GetEthGasLimit() uint64 {
	if m != nil {
		return m.EthGasLimit
	}
	return 0
}

type SidecarStateByEthHeightRequest struct {
	EthBlockHeight uint64 `protobuf:"varint,1,opt,name=EthBlockHeight,proto3" json:"EthBlockHeight,omitempty"`
}

func (m *SidecarStateByEthHeightRequest) Reset()         { *m = SidecarStateByEthHeightRequest{} }
func (m *SidecarStateByEthHeightRequest) String() string { return proto.CompactTextString(m) }
func (*SidecarStateByEthHeightRequest) ProtoMessage()    {}
func (*SidecarStateByEthHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f890d7da2148de8, []int{6}
}
func (m *SidecarStateByEthHeightRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SidecarStateByEthHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SidecarStateByEthHeightRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SidecarStateByEthHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SidecarStateByEthHeightRequest.Merge(m, src)
}
func (m *SidecarStateByEthHeightRequest) XXX_Size() int {
	return m.Size()
}
func (m *SidecarStateByEthHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SidecarStateByEthHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SidecarStateByEthHeightRequest proto.InternalMessageInfo

func (m *SidecarStateByEthHeightRequest) GetEthBlockHeight() uint64 {
	if m != nil {
		return m.EthBlockHeight
	}
	return 0
}

type SolanaTransactionRequest struct {
	TxSignature string `protobuf:"bytes,1,opt,name=TxSignature,proto3" json:"TxSignature,omitempty"`
}

func (m *SolanaTransactionRequest) Reset()         { *m = SolanaTransactionRequest{} }
func (m *SolanaTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*SolanaTransactionRequest) ProtoMessage()    {}
func (*SolanaTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f890d7da2148de8, []int{7}
}
func (m *SolanaTransactionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SolanaTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SolanaTransactionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SolanaTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolanaTransactionRequest.Merge(m, src)
}
func (m *SolanaTransactionRequest) XXX_Size() int {
	return m.Size()
}
func (m *SolanaTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SolanaTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SolanaTransactionRequest proto.InternalMessageInfo

func (m *SolanaTransactionRequest) GetTxSignature() string {
	if m != nil {
		return m.TxSignature
	}
	return ""
}

type SolanaTransactionResponse struct {
	TxSlot uint64 `protobuf:"varint,4,opt,name=TxSlot,proto3" json:"TxSlot,omitempty"`
}

func (m *SolanaTransactionResponse) Reset()         { *m = SolanaTransactionResponse{} }
func (m *SolanaTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*SolanaTransactionResponse) ProtoMessage()    {}
func (*SolanaTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f890d7da2148de8, []int{8}
}
func (m *SolanaTransactionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SolanaTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SolanaTransactionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SolanaTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolanaTransactionResponse.Merge(m, src)
}
func (m *SolanaTransactionResponse) XXX_Size() int {
	return m.Size()
}
func (m *SolanaTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SolanaTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SolanaTransactionResponse proto.InternalMessageInfo

func (m *SolanaTransactionResponse) GetTxSlot() uint64 {
	if m != nil {
		return m.TxSlot
	}
	return 0
}

type EthereumNonceAtHeightRequest struct {
	Address string `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Height  uint64 `protobuf:"varint,2,opt,name=Height,proto3" json:"Height,omitempty"`
}

func (m *EthereumNonceAtHeightRequest) Reset()         { *m = EthereumNonceAtHeightRequest{} }
func (m *EthereumNonceAtHeightRequest) String() string { return proto.CompactTextString(m) }
func (*EthereumNonceAtHeightRequest) ProtoMessage()    {}
func (*EthereumNonceAtHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f890d7da2148de8, []int{9}
}
func (m *EthereumNonceAtHeightRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EthereumNonceAtHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EthereumNonceAtHeightRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EthereumNonceAtHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EthereumNonceAtHeightRequest.Merge(m, src)
}
func (m *EthereumNonceAtHeightRequest) XXX_Size() int {
	return m.Size()
}
func (m *EthereumNonceAtHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EthereumNonceAtHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EthereumNonceAtHeightRequest proto.InternalMessageInfo

func (m *EthereumNonceAtHeightRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EthereumNonceAtHeightRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type EthereumNonceAtHeightResponse struct {
	Nonce uint64 `protobuf:"varint,1,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
}

func (m *EthereumNonceAtHeightResponse) Reset()         { *m = EthereumNonceAtHeightResponse{} }
func (m *EthereumNonceAtHeightResponse) String() string { return proto.CompactTextString(m) }
func (*EthereumNonceAtHeightResponse) ProtoMessage()    {}
func (*EthereumNonceAtHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f890d7da2148de8, []int{10}
}
func (m *EthereumNonceAtHeightResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EthereumNonceAtHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EthereumNonceAtHeightResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EthereumNonceAtHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EthereumNonceAtHeightResponse.Merge(m, src)
}
func (m *EthereumNonceAtHeightResponse) XXX_Size() int {
	return m.Size()
}
func (m *EthereumNonceAtHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EthereumNonceAtHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EthereumNonceAtHeightResponse proto.InternalMessageInfo

func (m *EthereumNonceAtHeightResponse) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func init() {
	proto.RegisterType((*LatestBitcoinBlockHeaderRequest)(nil), "api.LatestBitcoinBlockHeaderRequest")
	proto.RegisterType((*BitcoinBlockHeaderByHeightRequest)(nil), "api.BitcoinBlockHeaderByHeightRequest")
	proto.RegisterType((*BitcoinBlockHeaderResponse)(nil), "api.BitcoinBlockHeaderResponse")
	proto.RegisterType((*BTCBlockHeader)(nil), "api.BTCBlockHeader")
	proto.RegisterType((*SidecarStateRequest)(nil), "api.SidecarStateRequest")
	proto.RegisterType((*SidecarStateResponse)(nil), "api.SidecarStateResponse")
	proto.RegisterType((*SidecarStateByEthHeightRequest)(nil), "api.SidecarStateByEthHeightRequest")
	proto.RegisterType((*SolanaTransactionRequest)(nil), "api.SolanaTransactionRequest")
	proto.RegisterType((*SolanaTransactionResponse)(nil), "api.SolanaTransactionResponse")
	proto.RegisterType((*EthereumNonceAtHeightRequest)(nil), "api.EthereumNonceAtHeightRequest")
	proto.RegisterType((*EthereumNonceAtHeightResponse)(nil), "api.EthereumNonceAtHeightResponse")
}

func init() { proto.RegisterFile("api/sidecar_service.proto", fileDescriptor_9f890d7da2148de8) }

var fileDescriptor_9f890d7da2148de8 = []byte{
	// 753 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x4d, 0x4f, 0xdb, 0x4c,
	0x10, 0x8e, 0x21, 0x04, 0x31, 0x41, 0xbc, 0xd2, 0x92, 0xb7, 0x72, 0x5c, 0x30, 0xe0, 0x56, 0xa8,
	0xa7, 0x44, 0x02, 0x71, 0xab, 0x5a, 0x11, 0x88, 0x12, 0xa9, 0x94, 0x22, 0x27, 0xfd, 0x50, 0x0f,
	0x45, 0x1b, 0x67, 0x1b, 0x6f, 0x49, 0xbc, 0xae, 0x77, 0x13, 0x41, 0x7f, 0x44, 0x55, 0xa9, 0x7f,
	0xaa, 0x87, 0xaa, 0xe2, 0xd8, 0x63, 0x05, 0x7f, 0xa4, 0xf2, 0xae, 0x9d, 0x6c, 0xbe, 0xa0, 0x37,
	0xcf, 0x33, 0xb3, 0xcf, 0x33, 0x3b, 0x33, 0x3b, 0x86, 0x22, 0x0e, 0x69, 0x99, 0xd3, 0x36, 0xf1,
	0x70, 0x74, 0xce, 0x49, 0x34, 0xa0, 0x1e, 0x29, 0x85, 0x11, 0x13, 0x0c, 0x2d, 0xe2, 0x90, 0x5a,
	0x45, 0x8f, 0xf1, 0x1e, 0xe3, 0xe7, 0x12, 0x2a, 0x2b, 0x43, 0xf9, 0xad, 0x42, 0x87, 0x75, 0x98,
	0xc2, 0xe3, 0x2f, 0x85, 0x3a, 0xcf, 0x61, 0xeb, 0x04, 0x0b, 0xc2, 0x45, 0x85, 0x0a, 0x8f, 0xd1,
	0xa0, 0xd2, 0x65, 0xde, 0x45, 0x9d, 0xe0, 0x36, 0x89, 0x5c, 0xf2, 0xb9, 0x4f, 0xb8, 0x40, 0x1b,
	0xb0, 0x72, 0xe4, 0x63, 0x1a, 0x9c, 0xe2, 0x1e, 0x31, 0x8d, 0x6d, 0xe3, 0xc9, 0x8a, 0x3b, 0x02,
	0x1c, 0x0f, 0x76, 0xa6, 0x8f, 0x56, 0xae, 0xea, 0x84, 0x76, 0x7c, 0x91, 0x52, 0x6c, 0x43, 0x3e,
	0xf1, 0xc6, 0xa8, 0x24, 0x59, 0x74, 0x75, 0x68, 0x5c, 0x64, 0x61, 0x52, 0xe4, 0xbb, 0x01, 0xd6,
	0xac, 0x04, 0x79, 0xc8, 0x02, 0x4e, 0xd0, 0x01, 0xe4, 0x5b, 0x23, 0x58, 0xd2, 0xe7, 0xf7, 0xd6,
	0x4b, 0x38, 0xa4, 0xa5, 0x4a, 0xf3, 0x48, 0x3f, 0xa1, 0xc7, 0x4d, 0x66, 0xb5, 0x30, 0x33, 0xab,
	0x26, 0x0d, 0x13, 0xff, 0xa2, 0xf4, 0x8f, 0x00, 0xe7, 0x97, 0x01, 0x6b, 0xe3, 0xfc, 0xc8, 0x84,
	0xe5, 0x37, 0x24, 0xe2, 0x94, 0x05, 0xc9, 0x25, 0x53, 0x33, 0xa6, 0x3a, 0x8b, 0xc8, 0x40, 0x06,
	0xa7, 0x17, 0x1c, 0x02, 0xc8, 0x06, 0x78, 0x49, 0xa2, 0x8b, 0x2e, 0x71, 0x19, 0x53, 0x4a, 0x2b,
	0xae, 0x86, 0xa8, 0x44, 0x7a, 0xa4, 0x21, 0x70, 0x2f, 0x34, 0xb3, 0x69, 0x22, 0x09, 0x80, 0x10,
	0x64, 0x2b, 0x54, 0x70, 0x73, 0x49, 0x3a, 0xe4, 0x37, 0x2a, 0xc0, 0xd2, 0x29, 0x0b, 0x3c, 0x62,
	0xe6, 0x24, 0xa8, 0x8c, 0x98, 0x47, 0xa5, 0x8b, 0xb9, 0x6f, 0x2e, 0xab, 0x2c, 0x86, 0x80, 0xf3,
	0x3f, 0xac, 0x37, 0xd4, 0x6c, 0x35, 0x04, 0x16, 0x24, 0xe9, 0x9e, 0xf3, 0x75, 0x01, 0x0a, 0xe3,
	0x78, 0x52, 0xf7, 0x6d, 0xc8, 0x1f, 0x93, 0x2e, 0xe9, 0x60, 0x41, 0x59, 0xc0, 0xe5, 0x8d, 0x57,
	0x5d, 0x1d, 0x42, 0x0e, 0xac, 0xba, 0xaf, 0x8e, 0x5e, 0xbc, 0x6e, 0x1c, 0x9f, 0x45, 0xd4, 0x4b,
	0x3b, 0x3b, 0x86, 0xc5, 0x2c, 0xd5, 0x66, 0x7d, 0x18, 0xa2, 0x2e, 0xaf, 0x43, 0x68, 0x17, 0xd6,
	0xaa, 0xc2, 0xd7, 0x7b, 0x15, 0x97, 0x20, 0xeb, 0x4e, 0xa0, 0xb1, 0xda, 0x10, 0x89, 0x2f, 0xb8,
	0xa4, 0xd4, 0x74, 0x4c, 0xaa, 0x09, 0xbf, 0x86, 0xb9, 0x52, 0xcb, 0x49, 0x22, 0x1d, 0x1a, 0x45,
	0x9c, 0xd0, 0x1e, 0x15, 0xb2, 0x4a, 0xc3, 0x08, 0x09, 0x39, 0x75, 0xb0, 0xf5, 0x7a, 0x54, 0xae,
	0xaa, 0xc2, 0x1f, 0x1f, 0xf8, 0xe9, 0x8c, 0x8d, 0x59, 0x19, 0x3b, 0x4f, 0xc1, 0x6c, 0xb0, 0x2e,
	0x0e, 0x70, 0x33, 0xc2, 0x01, 0xc7, 0x5e, 0x5c, 0x35, 0xed, 0xd1, 0x34, 0x2f, 0x1b, 0xb4, 0x13,
	0x60, 0xd1, 0x8f, 0xd2, 0x97, 0xa7, 0x43, 0xce, 0x3e, 0x14, 0x67, 0x9c, 0x4e, 0x9a, 0xf3, 0x00,
	0x72, 0xcd, 0xcb, 0x46, 0x97, 0xa5, 0xc5, 0x4a, 0x2c, 0xe7, 0x0c, 0x36, 0xaa, 0xc2, 0x27, 0x11,
	0xe9, 0xf7, 0xe4, 0x4c, 0x1c, 0x8a, 0xf1, 0xd4, 0x4d, 0x58, 0x3e, 0x6c, 0xb7, 0x23, 0xc2, 0x79,
	0x22, 0x99, 0x9a, 0x31, 0xa3, 0xf6, 0x54, 0xb2, 0x6e, 0x62, 0x39, 0x07, 0xb0, 0x39, 0x87, 0x31,
	0x49, 0x65, 0x38, 0x8b, 0xaa, 0x08, 0xca, 0xd8, 0xfb, 0x99, 0x85, 0xb5, 0xb4, 0x8c, 0x6a, 0x93,
	0xa1, 0x3a, 0xfc, 0x57, 0x23, 0x42, 0xaf, 0x2d, 0x32, 0xe5, 0x33, 0x9e, 0x31, 0x96, 0x56, 0x71,
	0x86, 0x47, 0x09, 0x3a, 0x19, 0xf4, 0x01, 0xac, 0x09, 0x26, 0xad, 0x4b, 0xe8, 0xd1, 0xd4, 0xd1,
	0xe9, 0x1e, 0xde, 0xcd, 0xff, 0x09, 0x36, 0x6b, 0x44, 0xcc, 0xdf, 0x7c, 0x68, 0x57, 0xad, 0x9f,
	0xfb, 0x56, 0xa3, 0xb5, 0x35, 0x27, 0x4e, 0xd3, 0xfa, 0x08, 0x0f, 0x6b, 0x44, 0xcc, 0x5b, 0xd3,
	0xe8, 0xb1, 0x64, 0xb8, 0x67, 0x8b, 0xff, 0x8b, 0xce, 0x5b, 0x28, 0xc4, 0x35, 0x9b, 0x9c, 0x28,
	0xb4, 0xa9, 0x0a, 0x31, 0x67, 0x4e, 0x2d, 0x7b, 0x9e, 0x7b, 0x48, 0xec, 0x81, 0x59, 0x23, 0x62,
	0xe6, 0x8c, 0xa0, 0x1d, 0x79, 0xfa, 0xae, 0x89, 0xb4, 0x9c, 0xbb, 0x42, 0x52, 0x91, 0xca, 0xbb,
	0x1f, 0x37, 0xb6, 0x71, 0x7d, 0x63, 0x1b, 0x7f, 0x6e, 0x6c, 0xe3, 0xdb, 0xad, 0x9d, 0xb9, 0xbe,
	0xb5, 0x33, 0xbf, 0x6f, 0xed, 0xcc, 0xfb, 0x67, 0x1d, 0x2a, 0xfc, 0x7e, 0xab, 0xe4, 0xb1, 0x5e,
	0xf9, 0x0b, 0x09, 0x22, 0xe6, 0x5d, 0x74, 0x71, 0x8b, 0xa7, 0xdf, 0x65, 0x3c, 0xe0, 0xe5, 0x01,
	0xee, 0xd2, 0x36, 0x16, 0x2c, 0x3a, 0x4f, 0xfe, 0xae, 0x65, 0xf5, 0xab, 0xc4, 0x21, 0x6d, 0xe5,
	0xe4, 0xe7, 0xfe, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x15, 0x5b, 0xed, 0x11, 0x7d, 0x07, 0x00,
	0x00,
}

func (m *LatestBitcoinBlockHeaderRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LatestBitcoinBlockHeaderRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LatestBitcoinBlockHeaderRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChainName) > 0 {
		i -= len(m.ChainName)
		copy(dAtA[i:], m.ChainName)
		i = encodeVarintSidecarService(dAtA, i, uint64(len(m.ChainName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BitcoinBlockHeaderByHeightRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BitcoinBlockHeaderByHeightRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BitcoinBlockHeaderByHeightRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChainName) > 0 {
		i -= len(m.ChainName)
		copy(dAtA[i:], m.ChainName)
		i = encodeVarintSidecarService(dAtA, i, uint64(len(m.ChainName)))
		i--
		dAtA[i] = 0x12
	}
	if m.BlockHeight != 0 {
		i = encodeVarintSidecarService(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BitcoinBlockHeaderResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BitcoinBlockHeaderResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BitcoinBlockHeaderResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TipHeight != 0 {
		i = encodeVarintSidecarService(dAtA, i, uint64(m.TipHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.BlockHeight != 0 {
		i = encodeVarintSidecarService(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.BlockHeader != nil {
		{
			size, err := m.BlockHeader.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSidecarService(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BTCBlockHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BTCBlockHeader) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BTCBlockHeader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BlockHash) > 0 {
		i -= len(m.BlockHash)
		copy(dAtA[i:], m.BlockHash)
		i = encodeVarintSidecarService(dAtA, i, uint64(len(m.BlockHash)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Nonce != 0 {
		i = encodeVarintSidecarService(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x30
	}
	if m.Bits != 0 {
		i = encodeVarintSidecarService(dAtA, i, uint64(m.Bits))
		i--
		dAtA[i] = 0x28
	}
	if m.TimeStamp != 0 {
		i = encodeVarintSidecarService(dAtA, i, uint64(m.TimeStamp))
		i--
		dAtA[i] = 0x20
	}
	if len(m.MerkleRoot) > 0 {
		i -= len(m.MerkleRoot)
		copy(dAtA[i:], m.MerkleRoot)
		i = encodeVarintSidecarService(dAtA, i, uint64(len(m.MerkleRoot)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PrevBlock) > 0 {
		i -= len(m.PrevBlock)
		copy(dAtA[i:], m.PrevBlock)
		i = encodeVarintSidecarService(dAtA, i, uint64(len(m.PrevBlock)))
		i--
		dAtA[i] = 0x12
	}
	if m.Version != 0 {
		i = encodeVarintSidecarService(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SidecarStateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SidecarStateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SidecarStateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *SidecarStateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SidecarStateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SidecarStateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EthGasLimit != 0 {
		i = encodeVarintSidecarService(dAtA, i, uint64(m.EthGasLimit))
		i--
		dAtA[i] = 0x38
	}
	if m.EthGasPrice != 0 {
		i = encodeVarintSidecarService(dAtA, i, uint64(m.EthGasPrice))
		i--
		dAtA[i] = 0x30
	}
	if len(m.EthBlockHash) > 0 {
		i -= len(m.EthBlockHash)
		copy(dAtA[i:], m.EthBlockHash)
		i = encodeVarintSidecarService(dAtA, i, uint64(len(m.EthBlockHash)))
		i--
		dAtA[i] = 0x2a
	}
	if m.EthBlockHeight != 0 {
		i = encodeVarintSidecarService(dAtA, i, uint64(m.EthBlockHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ETHUSDPrice) > 0 {
		i -= len(m.ETHUSDPrice)
		copy(dAtA[i:], m.ETHUSDPrice)
		i = encodeVarintSidecarService(dAtA, i, uint64(len(m.ETHUSDPrice)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ROCKUSDPrice) > 0 {
		i -= len(m.ROCKUSDPrice)
		copy(dAtA[i:], m.ROCKUSDPrice)
		i = encodeVarintSidecarService(dAtA, i, uint64(len(m.ROCKUSDPrice)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Delegations) > 0 {
		i -= len(m.Delegations)
		copy(dAtA[i:], m.Delegations)
		i = encodeVarintSidecarService(dAtA, i, uint64(len(m.Delegations)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SidecarStateByEthHeightRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SidecarStateByEthHeightRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SidecarStateByEthHeightRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EthBlockHeight != 0 {
		i = encodeVarintSidecarService(dAtA, i, uint64(m.EthBlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SolanaTransactionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SolanaTransactionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SolanaTransactionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TxSignature) > 0 {
		i -= len(m.TxSignature)
		copy(dAtA[i:], m.TxSignature)
		i = encodeVarintSidecarService(dAtA, i, uint64(len(m.TxSignature)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SolanaTransactionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SolanaTransactionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SolanaTransactionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TxSlot != 0 {
		i = encodeVarintSidecarService(dAtA, i, uint64(m.TxSlot))
		i--
		dAtA[i] = 0x20
	}
	return len(dAtA) - i, nil
}

func (m *EthereumNonceAtHeightRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EthereumNonceAtHeightRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EthereumNonceAtHeightRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintSidecarService(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintSidecarService(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EthereumNonceAtHeightResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EthereumNonceAtHeightResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EthereumNonceAtHeightResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Nonce != 0 {
		i = encodeVarintSidecarService(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSidecarService(dAtA []byte, offset int, v uint64) int {
	offset -= sovSidecarService(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LatestBitcoinBlockHeaderRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainName)
	if l > 0 {
		n += 1 + l + sovSidecarService(uint64(l))
	}
	return n
}

func (m *BitcoinBlockHeaderByHeightRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockHeight != 0 {
		n += 1 + sovSidecarService(uint64(m.BlockHeight))
	}
	l = len(m.ChainName)
	if l > 0 {
		n += 1 + l + sovSidecarService(uint64(l))
	}
	return n
}

func (m *BitcoinBlockHeaderResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockHeader != nil {
		l = m.BlockHeader.Size()
		n += 1 + l + sovSidecarService(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovSidecarService(uint64(m.BlockHeight))
	}
	if m.TipHeight != 0 {
		n += 1 + sovSidecarService(uint64(m.TipHeight))
	}
	return n
}

func (m *BTCBlockHeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != 0 {
		n += 1 + sovSidecarService(uint64(m.Version))
	}
	l = len(m.PrevBlock)
	if l > 0 {
		n += 1 + l + sovSidecarService(uint64(l))
	}
	l = len(m.MerkleRoot)
	if l > 0 {
		n += 1 + l + sovSidecarService(uint64(l))
	}
	if m.TimeStamp != 0 {
		n += 1 + sovSidecarService(uint64(m.TimeStamp))
	}
	if m.Bits != 0 {
		n += 1 + sovSidecarService(uint64(m.Bits))
	}
	if m.Nonce != 0 {
		n += 1 + sovSidecarService(uint64(m.Nonce))
	}
	l = len(m.BlockHash)
	if l > 0 {
		n += 1 + l + sovSidecarService(uint64(l))
	}
	return n
}

func (m *SidecarStateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *SidecarStateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Delegations)
	if l > 0 {
		n += 1 + l + sovSidecarService(uint64(l))
	}
	l = len(m.ROCKUSDPrice)
	if l > 0 {
		n += 1 + l + sovSidecarService(uint64(l))
	}
	l = len(m.ETHUSDPrice)
	if l > 0 {
		n += 1 + l + sovSidecarService(uint64(l))
	}
	if m.EthBlockHeight != 0 {
		n += 1 + sovSidecarService(uint64(m.EthBlockHeight))
	}
	l = len(m.EthBlockHash)
	if l > 0 {
		n += 1 + l + sovSidecarService(uint64(l))
	}
	if m.EthGasPrice != 0 {
		n += 1 + sovSidecarService(uint64(m.EthGasPrice))
	}
	if m.EthGasLimit != 0 {
		n += 1 + sovSidecarService(uint64(m.EthGasLimit))
	}
	return n
}

func (m *SidecarStateByEthHeightRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EthBlockHeight != 0 {
		n += 1 + sovSidecarService(uint64(m.EthBlockHeight))
	}
	return n
}

func (m *SolanaTransactionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxSignature)
	if l > 0 {
		n += 1 + l + sovSidecarService(uint64(l))
	}
	return n
}

func (m *SolanaTransactionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TxSlot != 0 {
		n += 1 + sovSidecarService(uint64(m.TxSlot))
	}
	return n
}

func (m *EthereumNonceAtHeightRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovSidecarService(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovSidecarService(uint64(m.Height))
	}
	return n
}

func (m *EthereumNonceAtHeightResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Nonce != 0 {
		n += 1 + sovSidecarService(uint64(m.Nonce))
	}
	return n
}

func sovSidecarService(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSidecarService(x uint64) (n int) {
	return sovSidecarService(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LatestBitcoinBlockHeaderRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSidecarService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LatestBitcoinBlockHeaderRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LatestBitcoinBlockHeaderRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSidecarService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSidecarService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSidecarService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSidecarService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BitcoinBlockHeaderByHeightRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSidecarService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BitcoinBlockHeaderByHeightRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BitcoinBlockHeaderByHeightRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSidecarService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSidecarService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSidecarService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSidecarService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BitcoinBlockHeaderResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSidecarService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BitcoinBlockHeaderResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BitcoinBlockHeaderResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeader", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSidecarService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSidecarService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BlockHeader == nil {
				m.BlockHeader = &BTCBlockHeader{}
			}
			if err := m.BlockHeader.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TipHeight", wireType)
			}
			m.TipHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TipHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSidecarService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSidecarService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BTCBlockHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSidecarService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BTCBlockHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BTCBlockHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrevBlock", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSidecarService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSidecarService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrevBlock = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerkleRoot", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSidecarService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSidecarService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerkleRoot = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeStamp", wireType)
			}
			m.TimeStamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeStamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bits", wireType)
			}
			m.Bits = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Bits |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSidecarService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSidecarService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSidecarService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSidecarService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SidecarStateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSidecarService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SidecarStateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SidecarStateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipSidecarService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSidecarService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SidecarStateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSidecarService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SidecarStateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SidecarStateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegations", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSidecarService
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSidecarService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegations = append(m.Delegations[:0], dAtA[iNdEx:postIndex]...)
			if m.Delegations == nil {
				m.Delegations = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ROCKUSDPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSidecarService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSidecarService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ROCKUSDPrice = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ETHUSDPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSidecarService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSidecarService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ETHUSDPrice = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthBlockHeight", wireType)
			}
			m.EthBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EthBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthBlockHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSidecarService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSidecarService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EthBlockHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthGasPrice", wireType)
			}
			m.EthGasPrice = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EthGasPrice |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthGasLimit", wireType)
			}
			m.EthGasLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EthGasLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSidecarService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSidecarService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SidecarStateByEthHeightRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSidecarService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SidecarStateByEthHeightRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SidecarStateByEthHeightRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthBlockHeight", wireType)
			}
			m.EthBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EthBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSidecarService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSidecarService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SolanaTransactionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSidecarService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SolanaTransactionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SolanaTransactionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxSignature", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSidecarService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSidecarService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxSignature = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSidecarService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSidecarService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SolanaTransactionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSidecarService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SolanaTransactionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SolanaTransactionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxSlot", wireType)
			}
			m.TxSlot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxSlot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSidecarService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSidecarService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EthereumNonceAtHeightRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSidecarService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EthereumNonceAtHeightRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EthereumNonceAtHeightRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSidecarService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSidecarService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSidecarService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSidecarService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EthereumNonceAtHeightResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSidecarService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EthereumNonceAtHeightResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EthereumNonceAtHeightResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSidecarService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSidecarService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSidecarService(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSidecarService
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSidecarService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSidecarService
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSidecarService
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSidecarService
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSidecarService        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSidecarService          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSidecarService = fmt.Errorf("proto: unexpected end of group")
)
