---
name: test

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - edited
      - synchronize
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  unit-test:
    name: test
    runs-on: zenrock-devops
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
          cache-dependency-path: "**/*.sum"
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -race -v ./...
